// Copyright (c) 2012 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Top-level namespace-comment for operatableType
namespace operatable_type {
  dictionary DictType {
    int x;
    int y;
  };

  // Documentation for OperatableType.
  dictionary OperatableType {
    // Documentation for the String t.
    DOMString t;

    // Function returning nothing, taking nothing.
    static void voidFunc();

    // Function returning primitive type.
    static int intRetFunc();

    // Function returning dictionary.
    static DictType dictRetFunc();

    // Function taking primitive type.
    static void intArgFunc(int i);

    // Function taking dict type.
    static void dictArgFunc(DictType d);
  };
};
