#!/usr/bin/env bash
# Copyright (c) 2012 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Re-direct the arguments to dmprof.py.

BASEDIR=`dirname $0`
ARGV="$@"

PYTHONPATH=$BASEDIR/../python/google python \
    "$BASEDIR/dmprof.py" $ARGV
