name: Test Shaka Packager

description: |
  A reusable action to test Shaka Packager.
  Should be run after building Shaka Packager.

inputs:
  lib_type:
    description: A library type, either "static" or "shared".
    required: true
  build_type:
    description: A build type, either "Debug" or "Release".
    required: true
  build_type_suffix:
    description: A suffix to append to the build type in the output path.
    required: false
    default: ""
  exe_ext:
    description: The extension on executable files.
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Test
      shell: bash
      run: |
        # TODO(joeyparrish): Check for any test env setup
        #echo "::group::Prepare test environment"
        ## NOTE: Some of these tests must be run from the project root directory.
        #OUTDIR=build/${{ inputs.build_type }}${{ inputs.build_type_suffix }}
        #if [[ '${{ runner.os }}' == 'macOS' ]]; then
        #  export DYLD_FALLBACK_LIBRARY_PATH=$OUTDIR
        #fi
        #echo "::endgroup::"
        echo "::group::Test"
        (cd build; ctest -V)
        echo "::endgroup::"
