#!/usr/bin/env python
# Copyright (c) 2012 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
import os
import sys


sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

from telemetry.core import browser_options

def Main(args):
  options = browser_options.BrowserOptions()
  options.browser_type = 'list';
  parser = options.CreateParser('list_available_browsers')
  parser.parse_args()
  return 0

if __name__ == '__main__':
  sys.exit(Main(sys.argv[1:]))
