# Copyright 2022 Google LLC
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file or at
# https://developers.google.com/open-source/licenses/bsd

name: Build and Test PR

# Builds and tests on all combinations of OS, build type, and library type.
# Also builds the docs.
#
# Runs when a pull request is opened or updated.
#
# Can also be run manually for debugging purposes.
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      ref:
        description: "The ref to build and test."
        required: false
        type: string

# If another instance of this workflow is started for the same PR, cancel the
# old one.  If a PR is updated and a new test run is started, the old test run
# will be cancelled automatically to conserve resources.
concurrency:
  group: ${{ github.workflow }}-${{ inputs.ref || github.ref }}
  cancel-in-progress: true

jobs:
  settings:
    name: Settings
    uses: ./.github/workflows/settings.yaml

  build_and_test:
    needs: [settings]
    name: Build and test
    uses: ./.github/workflows/build.yaml
    with:
      ref: ${{ inputs.ref || github.ref }}
      self_hosted: ${{ needs.settings.outputs.self_hosted != '' }}
      debug: ${{ needs.settings.outputs.debug != '' }}
