name: Validate PR Title

on:
  # NOTE: The automated PRs from release-please-action do not seem to trigger
  # any of the default PR triggers (opened, synchronize, reopened).  So we need
  # additional types.  This is a good set that makes it easy to trigger the
  # workflow manually if needed.  This is not neccessary if your release-please
  # workflow uses a personal access token (PAT) from Shaka Bot.
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - assigned
      - labeled
      - ready_for_review
      - review_requested

jobs:
  main:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
